language: python
python:
  - "3.6"

#sudo: required

#Environment variables
# env:
#   - TRAVIS=yes

branches:
  only:
  - main

services:
  - docker

before_script:
  - docker build -t $DOCKER_USER/energym --build-arg ENERGYM_EXTRAS=[DRL,test] .
  
script:
  - docker run -it $DOCKER_USER/energym /bin/bash -c 'pytest tests -vv'
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  #Previusly set up in our own travis account
  - docker tag $DOCKER_USER/energym $DOCKER_USER/energym:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/energym:$TRAVIS_BUILD_NUMBER
  - docker tag $DOCKER_USER/energym $DOCKER_USER/energym:latest
  - docker push $DOCKER_USER/energym:latest



