language: python
python:
  - "3.6"

#sudo: required

#Environment variables
# env:
#   - TRAVIS=yes

services:
  - docker

before_script:
  - pip install -e .[extras]

script:
  - pytest ./tests/
#- docker build -t tests

# after_success:
#   - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  #Previusly set up in our own travis account
#   - docker tag back $DOCKER_USER/back:$TRAVIS_BUILD_NUMBER
#   - docker push $DOCKER_USER/back:$TRAVIS_BUILD_NUMBER
#   - docker tag back $DOCKER_USER/back:latest
#   - docker push $DOCKER_USER/back:latest



